### Import Dependencies

In [47]:
import openai
import pandas as pd

from qdrant_client import QdrantClient
from qdrant_client import models
from qdrant_client.models import VectorParams, Distance, SparseVectorParams, Modifier, PayloadSchemaType, PointStruct, Document, Prefetch, FusionQuery

### Create Qdrant collection for hybrid search

In [48]:
qdrant_client = QdrantClient(url="http://localhost:6333")

In [5]:
qdrant_client.create_collection(
    collection_name="Amazon-items-collection-01-hybrid-search",
    vectors_config={
        "text-embedding-3-small": VectorParams(size=1536, distance=Distance.COSINE)
    },
    sparse_vectors_config={
        "bm25": SparseVectorParams(modifier=Modifier.IDF)
    }
)

True

In [49]:
qdrant_client.create_payload_index(
    collection_name="Amazon-items-collection-01-hybrid-search",
    field_name="parent_asin",
    field_schema=PayloadSchemaType.KEYWORD
)

UpdateResult(operation_id=15, status=<UpdateStatus.COMPLETED: 'completed'>)

### Embedding Functions

In [50]:
def get_embedding(text, model="text-embedding-3-small"):
    response = openai.embeddings.create(
        input=text,
        model=model
    )
    return response.data[0].embedding

In [51]:
def get_embeddings_batch(text_list, model="text-embedding-3-small", batch_size=100):
    
    if len(text_list) <= batch_size:
        response = openai.embeddings.create(input=text_list, model=model)
        return [embedding.embedding for embedding in response.data]
    
    all_embeddings = []
    counter = 1
    for i in range(0, len(text_list), batch_size):
        batch = text_list[i:i + batch_size]
        response = openai.embeddings.create(input=batch, model=model)
        all_embeddings.extend([embedding.embedding for embedding in response.data])
        print(f"Processed {counter * batch_size} of {len(text_list)}")
        counter += 1
    
    return all_embeddings

### Read the sampled dataset with Amazon inventory data

In [52]:
df_items = pd.read_json(
    "../../data/meta_CDs_and_Vinyl_2022_2023_with_category_ratings_100_sample_1000.jsonl",
    lines=True
)

In [53]:
df_items.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together
0,Digital Music,"Girls, Girls, Girls",4.8,367,[],"[Girls, Girls, Girls — Mötley Crüe]",26.98,[{'thumb': 'https://m.media-amazon.com/images/...,[],Motley Crue Format: Vinyl,"[CDs & Vinyl, Rock, Hard Rock]",{'Product Dimensions': '0.16 x 12.32 x 12.48 i...,B09ZTFPVNB,NaN
1,Digital Music,"GarciaLive Vol. 18: November 2nd, 1974 - Keyst...",4.8,133,[],"[Produced from the original 1/4"" analog master...",12.49,[{'thumb': 'https://m.media-amazon.com/images/...,[],Jerry Garcia & Merl Saunders (Artist) Form...,"[CDs & Vinyl, Rock]",{'Product Dimensions': '5.59 x 0.39 x 4.92 inc...,B09YVCQC9V,NaN
2,Digital Music,RESIST,4.8,345,[],[],22.92,[{'thumb': 'https://m.media-amazon.com/images/...,[],Midnight Oil Format: Audio CD,"[CDs & Vinyl, AutoRip]",{'Product Dimensions': '4.9 x 5.4 x 0.3 inches...,B09MD1SRLF,NaN
3,Digital Music,Tana Talk 4,4.7,109,[],[2022 release. Benny the Butcher blazed a trai...,13.32,[{'thumb': 'https://m.media-amazon.com/images/...,[],Benny the Butcher Format: Audio CD,"[CDs & Vinyl, Rap & Hip-Hop]",{'Product Dimensions': '5.59 x 0.39 x 4.92 inc...,B09VPX9KFH,NaN
4,Digital Music,Chris Isaak Heart Shaped World (RSD Essential ...,4.7,409,[],[When Heart Shaped World was released in the s...,35.99,[{'thumb': 'https://m.media-amazon.com/images/...,[],Chris Isaak Format: Vinyl,"[CDs & Vinyl, Vinyl Store]",{'Product Dimensions': '12.2 x 0.2 x 12.2 inch...,B09TTSKVXY,NaN

### Preprocess title and features

In [54]:
def preprocess_description(row):
    return f"{row['title']} {' '.join(row['features'])}"

In [55]:
def extract_first_large_image(row):
    return row["images"][0].get("large", "")

In [56]:
df_items["preprocessed_description"] = df_items.apply(preprocess_description, axis=1)
df_items["image"] = df_items.apply(extract_first_large_image, axis=1)

In [57]:
df_items.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,preprocessed_description,image
0,Digital Music,"Girls, Girls, Girls",4.8,367,[],"[Girls, Girls, Girls — Mötley Crüe]",26.98,[{'thumb': 'https://m.media-amazon.com/images/...,[],Motley Crue Format: Vinyl,"[CDs & Vinyl, Rock, Hard Rock]",{'Product Dimensions': '0.16 x 12.32 x 12.48 i...,B09ZTFPVNB,NaN,"Girls, Girls, Girls",https://m.media-amazon.com/images/I/51yGOhceZU...
1,Digital Music,"GarciaLive Vol. 18: November 2nd, 1974 - Keyst...",4.8,133,[],"[Produced from the original 1/4"" analog master...",12.49,[{'thumb': 'https://m.media-amazon.com/images/...,[],Jerry Garcia & Merl Saunders (Artist) Form...,"[CDs & Vinyl, Rock]",{'Product Dimensions': '5.59 x 0.39 x 4.92 inc...,B09YVCQC9V,NaN,"GarciaLive Vol. 18: November 2nd, 1974 - Keyst...",https://m.media-amazon.com/images/I/51PU6YjqhO...
2,Digital Music,RESIST,4.8,345,[],[],22.92,[{'thumb': 'https://m.media-amazon.com/images/...,[],Midnight Oil Format: Audio CD,"[CDs & Vinyl, AutoRip]",{'Product Dimensions': '4.9 x 5.4 x 0.3 inches...,B09MD1SRLF,NaN,RESIST,https://m.media-amazon.com/images/I/31JpmDSjvM...
3,Digital Music,Tana Talk 4,4.7,109,[],[2022 release. Benny the Butcher blazed a trai...,13.32,[{'thumb': 'https://m.media-amazon.com/images/...,[],Benny the Butcher Format: Audio CD,"[CDs & Vinyl, Rap & Hip-Hop]",{'Product Dimensions': '5.59 x 0.39 x 4.92 inc...,B09VPX9KFH,NaN,Tana Talk 4,https://m.media-amazon.com/images/I/513cLiDTDS...
4,Digital Music,Chris Isaak Heart Shaped World (RSD Essential ...,4.7,409,[],[When Heart Shaped World was released in the s...,35.99,[{'thumb': 'https://m.media-amazon.com/images/...,[],Chris Isaak Format: Vinyl,"[CDs & Vinyl, Vinyl Store]",{'Product Dimensions': '12.2 x 0.2 x 12.2 inch...,B09TTSKVXY,NaN,Chris Isaak Heart Shaped World (RSD Essential ...,https://m.media-amazon.com/images/I/41awyiox6o...

In [58]:
list(df_items["preprocessed_description"].items())[0]

(0, 'Girls, Girls, Girls ')

In [59]:
list(df_items["image"].items())[0]

(0, 'https://m.media-amazon.com/images/I/51yGOhceZUL.jpg')

In [60]:
df_data_to_embed = df_items[["preprocessed_description", "image", "rating_number", "price", "average_rating", "parent_asin"]]

In [61]:
df_data_to_embed.head()

,preprocessed_description,image,rating_number,price,average_rating,parent_asin
0,"Girls, Girls, Girls",https://m.media-amazon.com/images/I/51yGOhceZU...,367,26.98,4.8,B09ZTFPVNB
1,"GarciaLive Vol. 18: November 2nd, 1974 - Keyst...",https://m.media-amazon.com/images/I/51PU6YjqhO...,133,12.49,4.8,B09YVCQC9V
2,RESIST,https://m.media-amazon.com/images/I/31JpmDSjvM...,345,22.92,4.8,B09MD1SRLF
3,Tana Talk 4,https://m.media-amazon.com/images/I/513cLiDTDS...,109,13.32,4.7,B09VPX9KFH
4,Chris Isaak Heart Shaped World (RSD Essential ...,https://m.media-amazon.com/images/I/41awyiox6o...,409,35.99,4.7,B09TTSKVXY

In [62]:
data_to_embed = df_data_to_embed.to_dict(orient="records")

In [63]:
data_to_embed

[{'preprocessed_description': 'Girls, Girls, Girls ',
  'image': 'https://m.media-amazon.com/images/I/51yGOhceZUL.jpg',
  'rating_number': 367,
  'price': 26.98,
  'average_rating': 4.8,
  'parent_asin': 'B09ZTFPVNB'},
 {'preprocessed_description': 'GarciaLive Vol. 18: November 2nd, 1974 - Keystone Berkeley[2 CD] ',
  'image': 'https://m.media-amazon.com/images/I/51PU6YjqhOL.jpg',
  'rating_number': 133,
  'price': 12.49,
  'average_rating': 4.8,
  'parent_asin': 'B09YVCQC9V'},
 {'preprocessed_description': 'RESIST ',
  'image': 'https://m.media-amazon.com/images/I/31JpmDSjvML.jpg',
  'rating_number': 345,
  'price': 22.92,
  'average_rating': 4.8,
  'parent_asin': 'B09MD1SRLF'},
 {'preprocessed_description': 'Tana Talk 4 ',
  'image': 'https://m.media-amazon.com/images/I/513cLiDTDSL.jpg',
  'rating_number': 109,
  'price': 13.32,
  'average_rating': 4.7,
  'parent_asin': 'B09VPX9KFH'},
 {'preprocessed_description': 'Chris Isaak Heart Shaped World (RSD Essential Edit ',
  'image': 'https://m.media-amazon.com/images/I/41awyiox6oL.jpg',
  'rating_number': 409,
  'price': 35.99,
  'average_rating': 4.7,
  'parent_asin': 'B09TTSKVXY'},
 {'preprocessed_description': "Maybe You'Ve Been Brainwashed Too Black ",
  'image': 'https://m.media-amazon.com/images/I/51dJEQd-6TL.jpg',
  'rating_number': 610,
  'price': 20.19,
  'average_rating': 4.7,
  'parent_asin': 'B0B92LF4CQ'},
 {'preprocessed_description': 'No More Worlds To Conquer ',
  'image': 'https://m.media-amazon.com/images/I/51I5pcfmgWL.jpg',
  'rating_number': 500,
  'price': 17.19,
  'average_rating': 4.7,
  'parent_asin': 'B09SP1GQYV'},
 {'preprocessed_description': 'Whitsitt Chapel ',
  'image': 'https://m.media-amazon.com/images/I/51iDgWLLPRL.jpg',
  'rating_number': 1220,
  'price': 13.97,
  'average_rating': 4.8,
  'parent_asin': 'B0BYL8ZN26'},
 {'preprocessed_description': 'Time, Tequila & Therapy ',
  'image': 'https://m.media-amazon.com/images/I/51c23qutTtL.jpg',
  'rating_number': 848,
  'price': 22.97,
  'average_rating': 4.8,
  'parent_asin': 'B09QH1W76K'},
 {'preprocessed_description': 'Snow Waltz ',
  'image': 'https://m.media-amazon.com/images/I/41qY52IqvoL.jpg',
  'rating_number': 542,
  'price': 10.89,
  'average_rating': 4.8,
  'parent_asin': 'B0B97PBJPW'},
 {'preprocessed_description': 'Christmas ',
  'image': 'https://m.media-amazon.com/images/I/51M5ZiFOnBL.jpg',
  'rating_number': 242,
  'price': 12.98,
  'average_rating': 4.7,
  'parent_asin': 'B09PRL5931'},
 {'preprocessed_description': 'Inner Spirit: The 1979 Concert At The Teatro General San Martín[2 CD] ',
  'image': 'https://m.media-amazon.com/images/I/51l1To8tKCL.jpg',
  'rating_number': 101,
  'price': 26.98,
  'average_rating': 4.8,
  'parent_asin': 'B09QNZBV2C'},
 {'preprocessed_description': 'Cotton Mouth Man ',
  'image': 'https://m.media-amazon.com/images/I/516Q9Ge-sNL.jpg',
  'rating_number': 143,
  'price': 17.49,
  'average_rating': 4.7,
  'parent_asin': 'B00BSWMIOK'},
 {'preprocessed_description': 'A Neil Diamond Christmas ',
  'image': 'https://m.media-amazon.com/images/I/51zW+xMa7aL.jpg',
  'rating_number': 111,
  'price': 12.99,
  'average_rating': 4.5,
  'parent_asin': 'B0BBRNMGSZ'},
 {'preprocessed_description': 'Mercury – Act 2[2 LP] ',
  'image': 'https://m.media-amazon.com/images/I/41pupxZvIjL.jpg',
  'rating_number': 110,
  'price': 34.63,
  'average_rating': 4.7,
  'parent_asin': 'B0BFXPLVG1'},
 {'preprocessed_description': 'Hard To Find Jukebox: Stereo Explosion 7 ',
  'image': 'https://m.media-amazon.com/images/I/51WqtQ1DrXL.jpg',
  'rating_number': 115,
  'price': 17.75,
  'average_rating': 4.8,
  'parent_asin': 'B0B3M8PDRX'},
 {'preprocessed_description': 'Listen To The Music ',
  'image': 'https://m.media-amazon.com/images/I/51G6MuHtDsL.jpg',
  'rating_number': 180,
  'price': 11.69,
  'average_rating': 4.7,
  'parent_asin': 'B0BLZG2YMG'},
 {'preprocessed_description': 'Carousel Of Time ',
  'image': 'https://m.media-amazon.com/images/I/61NwIo2QMnL.jpg',
  'rating_number': 111,
  'price': 14.59,
  'average_rating': 4.7,
  'parent_asin': 'B0B7F9JN5J'},
 {'preprocessed_description': 'Remember That You Will Die ',
  'image': 'https://m.media-amazon.com/images/I/61J6FNbCaXL.jpg',
  'rating_number': 188,
  'price': 26.98,
  'average_rating': 4.6,
  'parent_asin': 'B0B3HL8HV1'},
 {'preprocessed_description': 'All My Friends: Celebrating The Songs & Voice Of Gregg Allman [4 LP] ',
  'image': 'https://m.media-amazon.com/images/I/41dnzjWw9GL.jpg',
  'rating_number': 552,
  'price': 33.1,
  'average_rating': 4.8,
  'parent_asin': 'B0B61K8PQM'},
 {'preprocessed_description': "Tell Me That It's Over ",
  'image': 'https://m.media-amazon.com/images/I/41qtLFWZx-L.jpg',
  'rating_number': 302,
  'price': 21.98,
  'average_rating': 4.8,
  'parent_asin': 'B09RRZYVPL'},
 {'preprocessed_description': 'Love Is The New Black Gold ',
  'image': 'https://m.media-amazon.com/images/I/51tWVPOjO+L.jpg',
  'rating_number': 865,
  'price': 22.62,
  'average_rating': 4.7,
  'parent_asin': 'B09RX9RXVW'},
 {'preprocessed_description': 'Edge Of Thorns ',
  'image': 'https://m.media-amazon.com/images/I/51tJuvG1VgL.jpg',
  'rating_number': 471,
  'price': 43.49,
  'average_rating': 4.8,
  'parent_asin': 'B0B1YT99TB'},
 {'preprocessed_description': 'A Family Christmas ',
  'image': 'https://m.media-amazon.com/images/I/51xEMzYeLJL.jpg',
  'rating_number': 2746,
  'price': 13.39,
  'average_rating': 4.8,
  'parent_asin': 'B0BBMSLPDG'},
 {'preprocessed_description': "Everybody Knows It's Christmas[Candy Floss LP] ",
  'image': 'https://m.media-amazon.com/images/I/416KCqJvWFL.jpg',
  'rating_number': 167,
  'price': 16.66,
  'average_rating': 4.6,
  'parent_asin': 'B0BFLT4TJT'},
 {'preprocessed_description': 'In Cauda Venenum Extended Edition ',
  'image': 'https://m.media-amazon.com/images/I/51icYsaXELL.jpg',
  'rating_number': 995,
  'price': 16.98,
  'average_rating': 4.6,
  'parent_asin': 'B09WGR2M18'},
 {'preprocessed_description': 'LEGENDADDY[2 LP]       Explicit Lyrics ',
  'image': 'https://m.media-amazon.com/images/I/41FeI2wy83L.jpg',
  'rating_number': 167,
  'price': 34.28,
  'average_rating': 4.7,
  'parent_asin': 'B0BDTS1NDF'},
 {'preprocessed_description': 'The Click Deluxe Pressing ',
  'image': 'https://m.media-amazon.com/images/I/51wQrVn3XVL.jpg',
  'rating_number': 1199,
  'price': 32.99,
  'average_rating': 4.8,
  'parent_asin': 'B0BQCMT1VR'},
 {'preprocessed_description': 'Glitch Mode Photobook Version Random Cover ',
  'image': 'https://m.media-amazon.com/images/I/51hsxMtV-9L.jpg',
  'rating_number': 177,
  'price': 23.81,
  'average_rating': 4.7,
  'parent_asin': 'B09TNT5RYL'},
 {'preprocessed_description': 'Radiate Like This[LP] ',
  'image': 'https://m.media-amazon.com/images/I/21RLTem9nBL.jpg',
  'rating_number': 156,
  'price': 22.55,
  'average_rating': 4.7,
  'parent_asin': 'B09QWDNQH9'},
 {'preprocessed_description': 'A Beautiful Noise, The Neil Diamond Musical ',
  'image': 'https://m.media-amazon.com/images/I/51SGD78mo9L.jpg',
  'rating_number': 141,
  'price': 13.98,
  'average_rating': 4.6,
  'parent_asin': 'B0BGPZN9J4'},
 {'preprocessed_description': 'A Hundred Highways ',
  'image': 'https://m.media-amazon.com/images/I/512kpg6v4DL.jpg',
  'rating_number': 252,
  'price': 13.98,
  'average_rating': 4.9,
  'parent_asin': 'B0B8P232XQ'},
 {'preprocessed_description': 'Never Forget My Love ',
  'image': 'https://m.media-amazon.com/images/I/51G2KBlIq9L.jpg',
  'rating_number': 338,
  'price': 18.66,
  'average_rating': 4.4,
  'parent_asin': 'B09QJ2549C'},
 {'preprocessed_description': 'This River ',
  'image': 'https://m.media-amazon.com/images/I/519ZlFhxvzL.jpg',
  'rating_number': 216,
  'price': 13.95,
  'average_rating': 4.8,
  'parent_asin': 'B00BG475CK'},
 {'preprocessed_description': 'LEGENDADDY       Explicit Lyrics ',
  'image': 'https://m.media-amazon.com/images/I/41YjSSdhdYL.jpg',
  'rating_number': 193,
  'price': 13.14,
  'average_rating': 4.8,
  'parent_asin': 'B0B9CH2YK5'},
 {'preprocessed_description': 'GET ON BOARD ',
  'image': 'https://m.media-amazon.com/images/I/51hiBrS1nnL.jpg',
  'rating_number': 643,
  'price': 19.79,
  'average_rating': 4.6,
  'parent_asin': 'B09R84DXR1'},
 {'preprocessed_description': 'Balls Edition ',
  'image': 'https://m.media-amazon.com/images/I/31l1L-rp9eL.jpg',
  'rating_number': 117,
  'price': 31.98,
  'average_rating': 4.7,
  'parent_asin': 'B09T82XX5L'},
 {'preprocessed_description': 'John McLaughlin: The Montreux Years ',
  'image': 'https://m.media-amazon.com/images/I/51YdoH+mpUL.jpg',
  'rating_number': 132,
  'price': 17.99,
  'average_rating': 4.6,
  'parent_asin': 'B09KZLGW8F'},
 {'preprocessed_description': 'Midpoint ',
  'image': 'https://m.media-amazon.com/images/I/4131kjsgKBL.jpg',
  'rating_number': 177,
  'price': 29.99,
  'average_rating': 4.6,
  'parent_asin': 'B0B5PXSQJH'},
 {'preprocessed_description': 'Diabolical ',
  'image': 'https://m.media-amazon.com/images/I/51qE5bzUcNL.jpg',
  'rating_number': 226,
  'price': 14.43,
  'average_rating': 4.6,
  'parent_asin': 'B09PJL24QH'},
 {'preprocessed_description': 'Two Headed Freap (Blue Note Classic Vinyl Series)[LP] ',
  'image': 'https://m.media-amazon.com/images/I/31iZ28oK65L.jpg',
  'rating_number': 138,
  'price': 17.99,
  'average_rating': 4.7,
  'parent_asin': 'B09VYP9LRG'},
 {'preprocessed_description': 'Gold - Greatest Hits[Picture Disc 2 LP] ',
  'image': 'https://m.media-amazon.com/images/I/41uC--dS4lL.jpg',
  'rating_number': 104,
  'price': 34.99,
  'average_rating': 4.8,
  'parent_asin': 'B0B6GZQX8J'},
 {'preprocessed_description': 'The Last Resort: Greetings From[Transparent Green LP] ',
  'image': 'https://m.media-amazon.com/images/I/41ZKzn-pOuL.jpg',
  'rating_number': 398,
  'price': 20.54,
  'average_rating': 4.8,
  'parent_asin': 'B09TPQWVVL'},
 {'preprocessed_description': 'Do It for Love ',
  'image': 'https://m.media-amazon.com/images/I/51CwIUmDoZL.jpg',
  'rating_number': 234,
  'price': 15.96,
  'average_rating': 4.7,
  'parent_asin': 'B0B9HQB1TJ'},
 {'preprocessed_description': 'The Man From Waco ',
  'image': 'https://m.media-amazon.com/images/I/51NW4lWDzlL.jpg',
  'rating_number': 218,
  'price': 22.59,
  'average_rating': 4.8,
  'parent_asin': 'B0B6996WJY'},
 {'preprocessed_description': 'EBM ',
  'image': 'https://m.media-amazon.com/images/I/318CLz5xBGL.jpg',
  'rating_number': 263,
  'price': 14.98,
  'average_rating': 4.5,
  'parent_asin': 'B0B39VNTX1'},
 {'preprocessed_description': 'Candy-O (Rocktober Exclusive) ',
  'image': 'https://m.media-amazon.com/images/I/41niZB23kjL.jpg',
  'rating_number': 341,
  'price': 31.88,
  'average_rating': 4.7,
  'parent_asin': 'B0BFP9XKMC'},
 {'preprocessed_description': 'From The New World ',
  'image': 'https://m.media-amazon.com/images/I/51knsFhY4bL.jpg',
  'rating_number': 617,
  'price': 43.6,
  'average_rating': 4.4,
  'parent_asin': 'B09WH5FNJF'},
 {'preprocessed_description': 'Be A Man ',
  'image': 'https://m.media-amazon.com/images/I/51sboiv1iRL.jpg',
  'rating_number': 188,
  'price': 17.37,
  'average_rating': 4.7,
  'parent_asin': 'B0B78WSVQ7'},
 {'preprocessed_description': 'good kid, m.A.A.d city (10th Anniversary Edition) [2 LP]       Explicit Lyrics ',
  'image': 'https://m.media-amazon.com/images/I/31Gqr9s843L.jpg',
  'rating_number': 167,
  'price': 26.99,
  'average_rating': 4.7,
  'parent_asin': 'B0BC9V4LPV'},
 {'preprocessed_description': 'Will of The People ',
  'image': 'https://m.media-amazon.com/images/I/51vMCf2E-wL.jpg',
  'rating_number': 2243,
  'price': 12.54,
  'average_rating': 4.7,
  'parent_asin': 'B09VTVK4JY'},
 {'preprocessed_description': 'A Call to Arms       Explicit Lyrics ',
  'image': 'https://m.media-amazon.com/images/I/41TZYqBwU5L.jpg',
  'rating_number': 102,
  'price': 13.98,
  'average_rating': 4.8,
  'parent_asin': 'B09VWMGHQY'},
 {'preprocessed_description': 'MAXIDENT T-CRUSH ver. ',
  'image': 'https://m.media-amazon.com/images/I/418RNjDeaGL.jpg',
  'rating_number': 599,
  'price': 22.0,
  'average_rating': 4.7,
  'parent_asin': 'B0BCL2PZGF'},
 {'preprocessed_description': 'Black Panther: Wakanda Forever (Music From And Inspired By)[2 LP] ',
  'image': 'https://m.media-amazon.com/images/I/41ClX82UF9L.jpg',
  'rating_number': 224,
  'price': 31.16,
  'average_rating': 4.7,
  'parent_asin': 'B0BKQJNQRP'},
 {'preprocessed_description': 'NOT TiGHT[LP]       Explicit Lyrics ',
  'image': 'https://m.media-amazon.com/images/I/51M6Y7rp4eL.jpg',
  'rating_number': 184,
  'price': 25.99,
  'average_rating': 4.6,
  'parent_asin': 'B0B4RDCZW5'},
 {'preprocessed_description': 'Victims Of Deception - Limited Translucent Yellow ',
  'image': 'https://m.media-amazon.com/images/I/51oTqyG5tOL.jpg',
  'rating_number': 142,
  'price': 35.92,
  'average_rating': 4.7,
  'parent_asin': 'B09WKPJRMH'},
 {'preprocessed_description': 'On The Prowl       Explicit Lyrics ',
  'image': 'https://m.media-amazon.com/images/I/61YPgbXmbhL.jpg',
  'rating_number': 241,
  'price': 8.98,
  'average_rating': 4.6,
  'parent_asin': 'B0BM4XNTW7'},
 {'preprocessed_description': 'Meet The Moonlight ',
  'image': 'https://m.media-amazon.com/images/I/41HybYGQMDL.jpg',
  'rating_number': 457,
  'price': 8.0,
  'average_rating': 4.6,
  'parent_asin': 'B09XF6Y4LX'},
 {'preprocessed_description': 'Crücial Crüe - The Studio Albums 1981-1989 (Limited Edition CD Box) ',
  'image': 'https://m.media-amazon.com/images/I/41M9eFerQxL.jpg',
  'rating_number': 356,
  'price': 38.12,
  'average_rating': 4.8,
  'parent_asin': 'B0BL56MTV4'},
 {'preprocessed_description': 'Monday (BLACK & GREY SWIRL VINYL)       Explicit Lyrics ',
  'image': 'https://m.media-amazon.com/images/I/51UKrJU0PJL.jpg',
  'rating_number': 101,
  'price': 22.98,
  'average_rating': 4.7,
  'parent_asin': 'B07R826VJT'},
 {'preprocessed_description': 'Tomorrow Never Comes ',
  'image': 'https://m.media-amazon.com/images/I/51mxkZKBxYL.jpg',
  'rating_number': 170,
  'price': 11.0,
  'average_rating': 4.8,
  'parent_asin': 'B0C2VYZ1YF'},
 {'preprocessed_description': 'Blues Walk (Blue Note Classic Vinyl Series)[LP] ',
  'image': 'https://m.media-amazon.com/images/I/61HZUe2+iJL.jpg',
  'rating_number': 146,
  'price': 19.89,
  'average_rating': 4.8,
  'parent_asin': 'B09TVDHZQ7'},
 {'preprocessed_description': 'Entre eux deux ',
  'image': 'https://m.media-amazon.com/images/I/517s7HyfWVL.jpg',
  'rating_number': 209,
  'price': 13.69,
  'average_rating': 4.5,
  'parent_asin': 'B09QNYKHW4'},
 {'preprocessed_description': 'Flux Black Inside Transparent Electric Blue INDIE EX ',
  'image': 'https://m.media-amazon.com/images/I/61+bwJz7HJS.jpg',
  'rating_number': 286,
  'price': 25.98,
  'average_rating': 4.8,
  'parent_asin': 'B09SJ4JYMY'},
 {'preprocessed_description': 'View With A Room[LP] ',
  'image': 'https://m.media-amazon.com/images/I/31a8XI8oe5L.jpg',
  'rating_number': 111,
  'price': 22.99,
  'average_rating': 4.8,
  'parent_asin': 'B0B287C758'},
 {'preprocessed_description': 'Coming Home ',
  'image': 'https://m.media-amazon.com/images/I/41jg-FKItyL.jpg',
  'rating_number': 610,
  'price': 20.3,
  'average_rating': 4.7,
  'parent_asin': 'B0BYB5VV46'},
 {'preprocessed_description': 'Bluey Dance Mode Orange ',
  'image': 'https://m.media-amazon.com/images/I/51jAlqClv0L.jpg',
  'rating_number': 214,
  'price': 29.99,
  'average_rating': 4.8,
  'parent_asin': 'B0BRYFBCRF'},
 {'preprocessed_description': 'Erasure 2022 Expanded Edition ',
  'image': 'https://m.media-amazon.com/images/I/51Emb4PbyJL.jpg',
  'rating_number': 122,
  'price': 14.69,
  'average_rating': 4.8,
  'parent_asin': 'B0BGNKYPRJ'},
 {'preprocessed_description': 'On Avery Island ',
  'image': 'https://m.media-amazon.com/images/I/61PS5GetnQL.jpg',
  'rating_number': 297,
  'price': 23.99,
  'average_rating': 4.8,
  'parent_asin': 'B0BS1N1X15'},
 {'preprocessed_description': 'American Beauty [LP] ',
  'image': 'https://m.media-amazon.com/images/I/61hLB2eAcfL.jpg',
  'rating_number': 2802,
  'price': nan,
  'average_rating': 4.8,
  'parent_asin': 'B09SKKHR3Z'},
 {'preprocessed_description': 'Die For The Government ',
  'image': 'https://m.media-amazon.com/images/I/5162LRnXrKL.jpg',
  'rating_number': 140,
  'price': 9.98,
  'average_rating': 4.6,
  'parent_asin': 'B0BB38874Q'},
 {'preprocessed_description': "Now That's What I Call Christmas / Various - Red ",
  'image': 'https://m.media-amazon.com/images/I/41u-uW2KKNL.jpg',
  'rating_number': 332,
  'price': nan,
  'average_rating': 4.7,
  'parent_asin': 'B0BHGWCV4P'},
 {'preprocessed_description': 'The Wedding Singer Volume 2 - More Music From The Motion Picture Yellow Audiophile ',
  'image': 'https://m.media-amazon.com/images/I/51TgEzFwt1L.jpg',
  'rating_number': 255,
  'price': 36.98,
  'average_rating': 4.4,
  'parent_asin': 'B09SDG5PNB'},
 {'preprocessed_description': 'NOW Country 15 ',
  'image': 'https://m.media-amazon.com/images/I/61XL07XDyPL.jpg',
  'rating_number': 231,
  'price': 11.99,
  'average_rating': 4.7,
  'parent_asin': 'B09WYRPF69'},
 {'preprocessed_description': 'Devil You Know ',
  'image': 'https://m.media-amazon.com/images/I/619xKp4SkML.jpg',
  'rating_number': 115,
  'price': 11.15,
  'average_rating': 4.5,
  'parent_asin': 'B00GOIKAIY'},
 {'preprocessed_description': "So...How's Your Girl? ",
  'image': 'https://m.media-amazon.com/images/I/51+dbVpnVbL.jpg',
  'rating_number': 105,
  'price': nan,
  'average_rating': 4.6,
  'parent_asin': 'B09YQLN1XN'},
 {'preprocessed_description': 'Spellbound - Blue ',
  'image': 'https://m.media-amazon.com/images/I/51ccKlB-FnL.jpg',
  'rating_number': 200,
  'price': 35.96,
  'average_rating': 4.8,
  'parent_asin': 'B0B29F3YGM'},
 {'preprocessed_description': 'a lighter shade of blue ',
  'image': 'https://m.media-amazon.com/images/I/41f3FIUoVnL.jpg',
  'rating_number': 117,
  'price': 21.98,
  'average_rating': 4.6,
  'parent_asin': 'B09ZQ7VBGG'},
 {'preprocessed_description': 'RökFlöte ',
  'image': 'https://m.media-amazon.com/images/I/518lYfs0DIL.jpg',
  'rating_number': 365,
  'price': 51.05,
  'average_rating': 4.5,
  'parent_asin': 'B0BSJC3JRN'},
 {'preprocessed_description': 'Me/and/Dad[LP] ',
  'image': 'https://m.media-amazon.com/images/I/51x-z1c2xiL.jpg',
  'rating_number': 220,
  'price': 20.99,
  'average_rating': 4.8,
  'parent_asin': 'B0BF381YT9'},
 {'preprocessed_description': 'Pain Remains - Ltd. Black ',
  'image': 'https://m.media-amazon.com/images/I/41TKW1s6b6L.jpg',
  'rating_number': 255,
  'price': 46.99,
  'average_rating': 4.9,
  'parent_asin': 'B0B7QLFT24'},
 {'preprocessed_description': 'Beyond The Black - Limited Digibook Tracks ',
  'image': 'https://m.media-amazon.com/images/I/51yTv5uG9iL.jpg',
  'rating_number': 100,
  'price': 28.15,
  'average_rating': 4.7,
  'parent_asin': 'B0BHGBB3QH'},
 {'preprocessed_description': 'Infinite Disco ',
  'image': 'https://m.media-amazon.com/images/I/41qle6KDZQL.jpg',
  'rating_number': 423,
  'price': 21.49,
  'average_rating': 4.7,
  'parent_asin': 'B09WHGBMY5'},
 {'preprocessed_description': 'Morbidity Triumphant       Explicit Lyrics ',
  'image': 'https://m.media-amazon.com/images/I/51vPvu6iv8L.jpg',
  'rating_number': 114,
  'price': 14.06,
  'average_rating': 4.7,
  'parent_asin': 'B0B71XS6JH'},
 {'preprocessed_description': 'Aurora ',
  'image': 'https://m.media-amazon.com/images/I/5110rpn8-FL.jpg',
  'rating_number': 109,
  'price': 15.98,
  'average_rating': 4.5,
  'parent_asin': 'B0BTTKQT4S'},
 {'preprocessed_description': 'All-Time Greatest Hits ',
  'image': 'https://m.media-amazon.com/images/I/51TMTjIJXeL.jpg',
  'rating_number': 347,
  'price': 16.54,
  'average_rating': 4.8,
  'parent_asin': 'B09YP44VR9'},
 {'preprocessed_description': 'Cucumber Castle SHM ',
  'image': 'https://m.media-amazon.com/images/I/510-QUW68KL.jpg',
  'rating_number': 102,
  'price': 22.5,
  'average_rating': 4.7,
  'parent_asin': 'B0BD4XPYYM'},
 {'preprocessed_description': 'Europiana Encore ',
  'image': 'https://m.media-amazon.com/images/I/51LbtHJWpPL.jpg',
  'rating_number': 159,
  'price': 15.27,

In [27]:
len(data_to_embed)

2000

In [64]:
text_to_embed = [item["preprocessed_description"] for item in data_to_embed]

In [65]:
text_to_embed

['Girls, Girls, Girls ',
 'GarciaLive Vol. 18: November 2nd, 1974 - Keystone Berkeley[2 CD] ',
 'RESIST ',
 'Tana Talk 4 ',
 'Chris Isaak Heart Shaped World (RSD Essential Edit ',
 "Maybe You'Ve Been Brainwashed Too Black ",
 'No More Worlds To Conquer ',
 'Whitsitt Chapel ',
 'Time, Tequila & Therapy ',
 'Snow Waltz ',
 'Christmas ',
 'Inner Spirit: The 1979 Concert At The Teatro General San Martín[2 CD] ',
 'Cotton Mouth Man ',
 'A Neil Diamond Christmas ',
 'Mercury – Act 2[2 LP] ',
 'Hard To Find Jukebox: Stereo Explosion 7 ',
 'Listen To The Music ',
 'Carousel Of Time ',
 'Remember That You Will Die ',
 'All My Friends: Celebrating The Songs & Voice Of Gregg Allman [4 LP] ',
 "Tell Me That It's Over ",
 'Love Is The New Black Gold ',
 'Edge Of Thorns ',
 'A Family Christmas ',
 "Everybody Knows It's Christmas[Candy Floss LP] ",
 'In Cauda Venenum Extended Edition ',
 'LEGENDADDY[2 LP]       Explicit Lyrics ',
 'The Click Deluxe Pressing ',
 'Glitch Mode Photobook Version Random Cover ',
 'Radiate Like This[LP] ',
 'A Beautiful Noise, The Neil Diamond Musical ',
 'A Hundred Highways ',
 'Never Forget My Love ',
 'This River ',
 'LEGENDADDY       Explicit Lyrics ',
 'GET ON BOARD ',
 'Balls Edition ',
 'John McLaughlin: The Montreux Years ',
 'Midpoint ',
 'Diabolical ',
 'Two Headed Freap (Blue Note Classic Vinyl Series)[LP] ',
 'Gold - Greatest Hits[Picture Disc 2 LP] ',
 'The Last Resort: Greetings From[Transparent Green LP] ',
 'Do It for Love ',
 'The Man From Waco ',
 'EBM ',
 'Candy-O (Rocktober Exclusive) ',
 'From The New World ',
 'Be A Man ',
 'good kid, m.A.A.d city (10th Anniversary Edition) [2 LP]       Explicit Lyrics ',
 'Will of The People ',
 'A Call to Arms       Explicit Lyrics ',
 'MAXIDENT T-CRUSH ver. ',
 'Black Panther: Wakanda Forever (Music From And Inspired By)[2 LP] ',
 'NOT TiGHT[LP]       Explicit Lyrics ',
 'Victims Of Deception - Limited Translucent Yellow ',
 'On The Prowl       Explicit Lyrics ',
 'Meet The Moonlight ',
 'Crücial Crüe - The Studio Albums 1981-1989 (Limited Edition CD Box) ',
 'Monday (BLACK & GREY SWIRL VINYL)       Explicit Lyrics ',
 'Tomorrow Never Comes ',
 'Blues Walk (Blue Note Classic Vinyl Series)[LP] ',
 'Entre eux deux ',
 'Flux Black Inside Transparent Electric Blue INDIE EX ',
 'View With A Room[LP] ',
 'Coming Home ',
 'Bluey Dance Mode Orange ',
 'Erasure 2022 Expanded Edition ',
 'On Avery Island ',
 'American Beauty [LP] ',
 'Die For The Government ',
 "Now That's What I Call Christmas / Various - Red ",
 'The Wedding Singer Volume 2 - More Music From The Motion Picture Yellow Audiophile ',
 'NOW Country 15 ',
 'Devil You Know ',
 "So...How's Your Girl? ",
 'Spellbound - Blue ',
 'a lighter shade of blue ',
 'RökFlöte ',
 'Me/and/Dad[LP] ',
 'Pain Remains - Ltd. Black ',
 'Beyond The Black - Limited Digibook Tracks ',
 'Infinite Disco ',
 'Morbidity Triumphant       Explicit Lyrics ',
 'Aurora ',
 'All-Time Greatest Hits ',
 'Cucumber Castle SHM ',
 'Europiana Encore ',
 'Sing Me A Lullaby My Sweet Temptation       Explicit Lyrics ',
 'A Paranormal Evening with the Moonflower Society ',
 'Beyond the Black ',
 'This Is What It Feels Like[LP]       Explicit Lyrics ',
 'Lifted[LP] ',
 'Dynamite ',
 'The Hours Music from the Motion Picture Soundtrack ',
 '1972 ',
 "The Gang's All Here Limited Red ",
 'Finally Enough Love ',
 'Use Your Illusion I[2 LP] ',
 'RökFlöte ',
 'Bastards ',
 '…Baby One More Time ',
 'Asphalt Meadows ',
 'Live at the Capitol Theatre (CD/DVD) ',
 'Gentlemen Take Polaroids ',
 'Etazhi Silver ',
 'Where We Started[Black w/ Gold Swirl 2 LP] ',
 'Stormcock ',
 'Bob Marley With The Chineke! Orchestra ',
 "Fevers & Mirrors - 'Merlot Wave' ",
 'Thee Sacred Souls ',
 'America Turquoise 50th Anniversary ',
 'Zick Zack [CD Single] ',
 'Grave Dancers Union ',
 'Ready Now ',
 'Reckless ',
 'Theatre of Pain ',
 'Repentless - OxBlood & Orange Swirl w/ Mustard Splatter ',
 "Lil' Beethoven Edition ",
 'The Complete Harry Potter Film Music Collection ',
 "Rock 'N' Roll Fantasy: The Very Best Of Bad Company Limited/Clear Syeor ",
 'American Heartbreak ',
 'Joy ',
 'Hound Dog & Houserockers ',
 'Chloë and the Next 20th Century ',
 'Deltron 3030 Clear With Yellow & Black Vinyl ',
 'Going for the One ',
 'KIDZ BOP 2023 ',
 'Miasma ',
 'Dance Fever ',
 'Georgia Blue ',
 'Los Angeles Forum - April 26, 1969 ',
 'Somewhere To Elsewhere SILVER ',
 'Jose By J. Balvin- Limited Edition Purple & Blue Colored Vinyl with Poster ',
 'Keep Your Courage ',
 'Fall Out Boy - Infinity On High 15 Year Anniversary ',
 'Kiss[LP] ',
 'Bronco ',
 "SEVENTEEN 4th Album 'Face the Sun'[ep.5 Pioneer] ",
 'Last Splash ',
 'The Dark Side Of The Moon (50th Anniversary Deluxe Remaster) ',
 'Eyes Of Oblivion ',
 'Madman Across The Water 50th Anniversary [4LP Box Set] ',
 'A Night of a Thousand Vampires ',
 '‘Indigo’[LP] ',
 'Nothing To Fear ',
 'Higher Than Heaven[Deluxe CD]       Explicit Lyrics ',
 'The Rolling Stones In Mono[16 Color LP Box Set] ',
 'Multitude - Exclusive Limited Edition Green Colored Vinyl LP ',
 'Forgotten in Space ',
 'Blue Rev ',
 'Unleash - incl. ',
 'Envy Of None ',
 "Live At Montreux Jazz Festival '07 ",
 'Revolver Special Edition[LP] ',
 'Everyday Is Christmas ',
 'Billlie The Collective Soul and Unconscious : Chapter one 2nd Mini Album Unconscious Version CD+76p PhotoBook+1p ID Photo+2p PhotoCard+1p Polaroid+Layered Card+Sticker+Tracking Sealed ',
 'Whenever You Need Somebody 2022 ',
 'Stoned Cold Country ',
 "Don't Look Back ",
 'Modern Primitive ',
 'SUPERACHE[Ruby Red LP]       Explicit Lyrics ',
 "You're Gonna Miss It All - Olive Green ",
 '(watch my moves) ',
 "School's Out Expanded & Remastered ",
 'Legend[2 CD]       Explicit Lyrics ',
 'Portrait In Jazz Bonus Tracks ',
 'Tornillo ',
 'EL MIRADOR ',
 'Their Satanic Majesties Request[LP] ',
 'CHECKMATE[YEJI Ver.] ',
 'Moving Pictures (40th Anniversary)[Super Deluxe 3CD/5LP/Blu-Ray] ',
 'State Of Deception deluxe Version ',
 "Olivia's Greatest Hits Vol. 2 (Deluxe Edition)[2 LP] ",
 'Midnights[Blood Moon Edition] [Edited]       Clean Version ',
 'Love ',
 'Funky Nothingness ',
 'Villains (OPAQUE WHITE VINYL) ',
 'Retropolitan ',
 'Spinning The Truth Around ',
 'Space Is The Place SILVER, GOLD & LIME ',
 'Kingfish ',
 'HOLY FVCK       Explicit Lyrics ',
 'Dying of Everything ',
 'Taylor Swift - Midnights: Lavender Edition Exclusive ',
 'Universal ',
 'ALPHA ',
 'Detour ',
 'Big Time ',
 'The Captain And Me Anniversary ',
 'Mirror To The Sky ',
 'A-Z ',
 'Wilderness of Mirrors ',
 'As Recorded At Madison Square Garden - Limited White Marble ',
 'Jam & Lewis, Volume One ',
 'Wilderness of Mirrors ',
 'BETWEEN 1&2[Cryptography ver.] ',
 'Cave World       Explicit Lyrics ',
 "Live In Cleveland '77 ",
 'Killing The Dragon Red & Orange Swirl ',
 'Revolver Special Edition[5 CD] ',
 'Walk On Water ',
 'Giant Steps ',
 'Around The World (Restored & Expanded)[CD/DVD] ',
 'Direction of the Heart ',
 'Only The Strong Survive ',
 '3 Feet High And Rising ',
 'The Age of Quarrel ',
 'I NEVER DIE ',
 'How Dare You! - 180gm ',
 'Because The Internet - Exclusive Limited Edition Pink Toes Colored Vinyl 2 LP ',
 'mainstream sellout       Explicit Lyrics ',
 'READY TO BE[BE ver.] ',
 '6 Feet Deep - Exclusive ROTM Club Edition Black & Silver Splatter Vinyl LP ',
 'The Disney Book[Deluxe 2 CD] ',
 'My Favorite Things 2022 ',
 "SEVENTEEN 4th Album 'Face the Sun'[ep.2 Shadow] ",
 'George Straits #1s Volume 1 - Exclusive Limited Edition Blue Colored Vinyl LP ',
 'Toast ',
 'Vaxis II: A Window of the Waking Mind ',
 '5-STAR LIMITED Ver. ',
 'Authorized Greatest Hits ',
 'For Those Which Are Asleep ',
 'Familia ',
 'Awaken My Love Exclusive ',
 'McCartney I / II / III[3 LP Box Set] ',
 'Where The Light Goes ',
 'Rashomon white ',
 'Waiting For Columbus ',
 'Lado A Lado B ',
 'Royce Hall 1971 ',
 'KISS Off The Soundboard: Live In Virginia Beach[2 CD] ',
 'Live At Yankee Stadium ',
 'The Mothers 1971[Super Deluxe 8 CD] ',
 'The Blonde & Pink Albums ',
 'Conspiranoid[White LP] ',
 'Titans Of Creation - Video Album ',
 'Life Moves Pretty Fast - The John Hughes Mixtapes / Various - 140gm Black ',
 'Time Fades Away ',
 'The Phoenix ',
 'Life Is Like A Song[LP] ',
 'Skinty Fia ',
 'Rad Wings of Destiny ',
 'Divisive ',
 'Lifted ',
 'Wish RSD 2022 Picture Disc Vinyl ',
 'Ego Trip ',
 'The Last Of Us Original Soundtrack ',
 'Complete RCA Album Collection ',
 'Animals (2018 Remix) ',
 'Country Ghetto ',
 'Live Songs For Beginners, Wild Tales ',
 'Spirits - White ',
 'I Go To The Rock: The Gospel Music Of Whitney Houston ',
 'Marry Me Soundtrack ',
 'Dirty Honey ',
 'American Heartbreak ',
 'We Are The Apocalypse ',
 'Gifts From The Holy Ghost ',
 'Frances the Mute ',
 'Empire Central ',
 'Whipped! (MILKY CLEAR "WHIPPED CREAM" VINYL) ',
 'i used to think i could fly       Explicit Lyrics ',
 'Culture III[2 LP]       Explicit Lyrics ',
 'MUSIC FROM THE MOTION PICTURE YOU\'VE GOT MAIL ("Highlighter Yellow" Color Vinyl) ',
 'BORN PINK[Standard CD Boxset – Version C / GRAY]       Explicit Lyrics ',
 'Growing Up ',
 'Evenings At The Village Gate: John Coltrane With Eric Dolphy ',
 'A Light for Attracting Attention ',
 'Infamous Angel ',
 'Jack White Entering Heaven Alive (Indie Exclusive, ',
 '5SOS5 ',
 'Asphalt Meadows ',
 'Patient Number 9 ',
 'Too Fast For Love ',
 'Licked Live In NYC[2 CD] ',
 'Heart On My Sleeve       Explicit Lyrics ',
 'His Hand In Mine ',
 'Conditions Of My Parole ',
 'Guardians Of The Galaxy - Exclusive Limited Edition Red & Yellow Colored Vinyl 2LP ',
 'Vaxis II: A Window of the Waking Mind ',
 'Big Bad Voodoo Daddy (Americana Deluxe)—25th Anniversary (CLEAR WITH RED & YELLOW SWIRL VINYL) ',
 'Now Yearbook 1986 / Various - Limited ',
 'Dive Deep - Limited Turquoise ',
 'Impossible Princess Limited Orange 12” ',
 'Karma (Verve Acoustic Sounds Series)[LP] ',
 'Black Radio III ',
 'House of Pain Fine Malt Lyrics 30 Years ',
 'Ghost In The Machine[Picture Disc]       Explicit Lyrics ',
 'The Agony & Ecstasy of Watain (Lim. ',
 'Donna Summer: 40th Anniversary Picture ',
 'Live Songs For Beginners, Wild Tales ',
 'Official Release Series Discs 13, 14, 20 & 21 ',
 'Regimental Sgt. Zippo ',
 'Serendipity: Music from the Miramax Motion Picture ("SKATING RINK" WHITE VINYL) ',
 'A Paranormal Evening with the Moonflower Society ',
 'Survival Of The Sickest ',
 'Dear Evan Hansen (Original Motion Picture Soundtrack)[Blue 2 LP] ',
 "Now That's What I Call A Massive 80s Party / Various ",
 'Shadows Fall The Art of Balance (RSD11.25.22) Reco ',
 'En El Palacio De Bellas Artes ',
 'Dawn FM by The Weekend Autograph       explicit_lyrics ',
 "All's Well That Ends Well       Explicit Lyrics ",
 "We've Been Going About This All Wrong ",
 'Greatest Hits - SPLATTER ',
 'Dirt Does Dylan ',
 'Red Moon In Venus       Explicit Lyrics ',
 'Winning Hand ',
 'The Electric Mayhem (Original Soundtrack)[Translucent Purple/Blue Swirl LP] ',
 'ID.Entity - Limited Orange ',
 "'Indigo' Book Edition ",
 'The Lost Boys Soundtrack Metallic Gold Audiophile ',
 'Unlimited Love ',
 'Player ',
 'Opvs Contra Natvram ',
 "NOW That's What I Call Music! Vol. 83 ",
 'Heroes & Villains[LP]       Explicit Lyrics ',
 'The Asylum Albums 1972–1975 ',
 'Tales Of Time[CD/Blu-ray] ',
 'A Charlie Brown Christmas (Deluxe Edition) ',
 'Eternal Nightmare ',
 'Sounds Of Summer: The Very Best Of The Beach Boys[Remastered] ',
 'Diamonds & Dancefloors ',
 'Hi-Fi Christmas Guitar ',
 'A Neil Diamond Christmas[Deluxe 2 CD] ',
 'Bridges ',
 'Art Pepper Meets The Rhythm Section[Contemporary Acoustic Sounds Series] [Stereo] ',
 'Let There Be Witchery ',
 'a lighter shade of blue ',
 'SEVEN ',
 'Cowboy Tears ',
 'Fossora ',
 'Humble Quest ',
 'Supergrass ',
 'Dinosaur ',
 'Best Of: Living the Dream ',
 'Danse Macabre ',
 'Lauren Daigle (Amazon Exclusive CD + Poster) ',
 "Did you know that there's a tunnel under Ocean Blvd       Explicit Lyrics ",
 'Zeit Marbled ',
 'Against The Odds: 1974-1982[3 CD] ',
 'Fashion Nugget       Explicit Lyrics ',
 '(watch my moves)[2 LP] ',
 'Macadelic (10th Anniversary)[Deluxe Silver 2 LP]       Explicit Lyrics ',
 'Theatre of Pain ',
 'Pain Remains       Explicit Lyrics ',
 'Detour[LP] ',
 'Memento Mori ',
 'ICONIC[2 LP] ',
 'Highway 61 Revisited ',
 'Life After Death - Exclusive Limited Edition Silver Colored Vinyl 2 LP (25th Anniversary From Biggie Smalls) ',
 'Live In London-Hammersmith Apollo 1993 Marbled ',
 'Around The World (Restored & Expanded)[CD/Blu-ray] ',
 'If ',
 'Chaos & Colour Deluxe ',
 "O'Jays Collectors Items Greatest Hits [VINYL ALBUM] ",
 'Red Green Blue ',
 'The Lockdown Sessions ',
 'Autofiction ',
 'The Testament ',
 'River Fools and Mountain Saints ',
 'Devil May Care (TRANSLUCENT RED VINYL) ',
 'Linger Awhile[LP] ',
 'The Original Recordings       Explicit Lyrics ',
 'Live at the Greek Theater 2019 ',
 'KEY Parental Advisory Content       explicit_lyrics ',
 'Mark Tremonti Sings Frank Sinatra ',
 'Home Alone Christmas - Exclusive Limited Edition Red Colored Vinyl LP ',
 'Carry Me Home ',
 'Direction of the Heart ',
 'We Were Dead Before The Ship Even Sank Translucent ',
 'Blue Hawaii Limited Turquoise ',
 'Totem ',
 'RENAISSANCE ',
 'Eldorado ',
 "#1's - Volume 1 ",
 '(self-titled)[LP]       Explicit Lyrics ',
 'The Call Of The Void ',
 'Pretenders 2018 ',
 'Gutter Ballet ',
 'The Years Of Decay ',
 'Peace...Like A River[Deluxe 2 CD] ',
 'Heart Is Strange - Deluxe ',
 'Bridgerton Aqua Record, Music / Covers From The Original Series by Kris Bowers ',
 'The Piper at the Gates of Dawn Version ',
 '3 Feet High And Rising ',
 'Adobe Sessions ',
 'Accident of Birth ',
 'XL ',
 'Personalidad ',
 'Black Acid Soul ',
 'Wish 30th Anniversary ',
 'Viva Las Vengeance ',
 'Killer Expanded & Remastered ',
 'Nocturne ',
 'Attack on Titan Season 1 Original Soundtrack Clear with Black & Sky Blue Splatter Colored Vinyl 3LP (Numbered /500) ',
 'Faith in the Future Deluxe Zine ',
 'Digital Noise Alliance ',
 'Totem - Blue ',
 'Bridges ',
 'Honky Chateau[50th Anniversary 2 LP] ',
 'Open Mind: The Best Of Blackfield ',
 'Revelations of Oblivion - Black ',
 'Zeit[2 LP] ',
 'Promised Land Translucent Gold Audiophile ',
 'Crawfish Fiesta ',
 'Showdown ',
 'An Appointment With Mr Yeats 2022 ',
 'Live Evil 40th Anniversary Super Deluxe ',
 'Supergrass Neon ',
 'Every Five Seconds ',
 'Beatopia ',
 'Encanto Original Sountrack Spanish Version ',
 'Nevermind ',
 "Now That's What I Call Pride / Various ",
 'Welfare Jazz Deluxe ',
 'Warm Chris ',
 'Introvert Extrovert ',
 'Forrest Gump The Soundtrack - Exclusive Limited Edition Red & Blue Colored Vinyl 2LP ',
 'The Car ',
 '12 x 5[LP] ',
 'The Blonde & Pink Albums ',
 'GRRR Live![2 CD/Blu-ray] ',
 'Just Like That... ',
 'Moving Pictures (40th Anniversary)[Deluxe 5 LP] ',
 "We've Been Going About This All Wrong - Marbled Smoke ",
 'Frozen 2 (The Original Soundtrack) [CD] ',
 'Start Again ',
 "minisode 2: Thursday's Child[HATE ver.] ",
 'This Is The Heavy       Explicit Lyrics ',
 'Things Happen That Way - Exclusive Limited Edition Blue Colored Vinyl LP ',
 'Gettin’ Old (Amazon Exclusive Edition) ',
 'Dangerous: The Double Album[2 CD]       Explicit Lyrics ',
 'Electra Heart Platinum Blonde Edition ',
 'GRRR Live![3 LP] ',
 'The Fighter ',
 'I Am The Moon: IV. Farewell ',
 'Mirror To The Sky ',
 'I Can Hear The Heart Beating As One-25th Anniversary Edition (YELLOW VINYL) ',
 'THE DEATH OF PEACE OF MIND Silver       Explicit Lyrics ',
 'Royce Hall 1971 ',
 'A Heartless Portrait The Orphean Testament ',
 'Slipknot ',
 'Genuine Houserockin Christmas ',
 'Lalalalovesongs ',
 'An Evening With Silk Sonic - Exclusive Limited Edition Yellow Colored Vinyl LP ',
 'The Loneliest Time[LP]       Explicit Lyrics ',
 'Midnights[Moonstone Blue Edition] [Edited]       Clean Version ',
 'Asia in Asia - Live at The Budokan, Tokyo, 1983 Deluxe ',
 'IM NAYEON[YEON ver.] ',
 'Inferno ',
 'Girl Of My Dreams       Explicit Lyrics ',
 'Remember The Future picture ',
 "The Magician's Birthday ",
 'No Heavy Petting 2023 ',
 'Witch ',
 'PORTALS ',
 'Uncivil War ',
 'Queen[LP] ',
 'Speed of Heat ',
 'Against The Odds: 1974-1982[8 CD] ',
 'Ted Nugent Spirit of The Wild (RSD11.25.22) Record ',
 'Peace...Like A River[2 LP] ',
 'Life, Love & Pain - Pink ',
 'Greatest Hits : My Prerogative ',
 'Milk & Cookies: A Merry Crowder Christmas ',
 'Spiceworld 25[Picture Disc LP] ',
 'King Of Hearts ',
 'Seven Turns ',
 'Seven Psalms ',
 'SMITHEREENS ',
 'Wrong Side of Paradise ',
 'READY TO BE[TO ver.] ',
 'Midnights[Jade Green Edition] [Edited]       Clean Version ',
 'Vol. 10       Explicit Lyrics ',
 'Chasing Ghosts ',
 'See What You Started By Continuing ',
 'The A&M CD Box Set 1970-1975[8 CD] ',
 'Black Laden Crown - Orange ',
 'NOT TiGHT       Explicit Lyrics ',
 '3 Feet High And Rising (Amazon Exclusive Blue Vinyl) ',
 "The Blues Don't Lie ",
 'CHICAGO - Chicago At Carnegie Hall, April 9, 1971 RSD 2022 ',
 'Streets - A Rock Opera ',
 'Enemies of Reality ',
 'Yoshimi Battles the Pink Robots 20th Anniversary ',
 'Hey Doll Baby ',
 'Beatopia[LP] ',
 'Balls ',
 'Just The Two Of Us: The Duets Collection (Volume One) ',
 'Rescue Story ',
 'Girls - The 2nd Mini Album KWANGYA Version ',
 'SLEEPLESS IN SEATTLE--Original Motion Picture Soundtrack (Sunset Vinyl Edition) ',
 'Neon Noir ',
 'Nothing But the Blues ',
 'Foregone ',
 'Music To Be Murdered By: Side B With Alternate Cover Art ',
 'It’s A Shame About Ray DELUXE ',
 'Midnights[Jade Green Edition LP]       Explicit Lyrics ',
 'H.A.R.D.       Explicit Lyrics ',
 'Kvitravn - First Flight Of The White Raven ',
 'Nancy & Lee ',
 'TEKKNO       Explicit Lyrics ',
 'Flesh & Blood ',
 'Black Tie White Noise 2021 ',
 'Hank Williams Jr. Rich White Honky Blues [Explicit ',
 'Hidden Gems - Opaque Sky Blue ',
 'Sonder ',
 'Donda[Deluxe 4 LP] ',
 'Rise And Fall, Rage And Grace [15th Anniversary Edition] [LP + 7" Single] ',
 'Shrine white ',
 "Zappa '80: Mudd Club/Munich[3 CD] ",
 'Live In Chicago ',
 'AURORA ',
 "SEVENTEEN 4th Album 'Face the Sun'[ep.3 Ray] ",
 'Live At The El Mocambo[4 LP] ',
 "It's Almost Dry[LP]       Explicit Lyrics ",
 'Twelve Carat Toothache       Clean Version ',
 'In The Wild ',
 'Crosby, Stills & Nash [LP] ',
 'Spiceworld 25[Deluxe 2 CD] ',
 'I NEVER LIKED YOU       Explicit Lyrics ',
 'Vibrating ',
 'Encanto (Original Motion Picture Soundtrack)[Highlights] [LP] ',
 'Patient Number 9 ',
 'Santa Baby ',
 'Donda Deluxe ',
 'CHARLIE ',
 'Color Decay ',
 'Who Cares? (Amazon Exclusive CD - Signed Insert) ',
 'Pirates ',
 'Las Vegas International Presents Elvis – Now 1971 Digibook) ',
 'The Astronaut[VERSION 02] ',
 'BE HERE NOW ',
 "It's a Man's World 2023 ",
 'Sweet Evil Sun ',
 'Gloria[LP] ',
 'Blues Without You ',
 'Stephen Stills Live At Berkeley 1971 ',
 'War Of Art Black ',
 'ELECTRONIC - Remix Mini Album RSD 2022 ',
 'Shout At The Devil ',
 'Bad Reputation ',
 'the record       Explicit Lyrics ',
 'The Alchemy Project ',
 'Gone Now Gold Palate ',
 'Watertown[LP] ',
 'Lighting Up The Sky ',
 'I love ',
 'Fauna ',
 'Chloë and the Next 20th Century ',
 'Honky Chateau[50th Anniversary 2 CD] ',
 'About Last Night...[LP]       Explicit Lyrics ',
 'Entering Heaven Alive ',
 'Official Release Series Discs 13, 14, 20 & 21 ',
 'Hi-Fi Christmas Guitar ',
 '12th of June ',
 'Last Night In The Bittersweet ',
 'Fever ',
 'The Who With Orchestra: Live At Wembley[2 CD/Blu-ray Audio] ',
 'Animals (2018 Remix) ',
 'The Journey Part 1 ',
 'Seven ',
 'Physical Thrills ',
 'City Burials ',
 'From silence to somewhere ',
 'What’s It Gonna Take?[2 LP] ',
 'Big Time opaque Pink ',
 'The Holographic Principle - Splatter ',
 'Other Worlds ',
 'Generator - Anniversary Edition ',
 'Now Yearbook Extra 1985 / Various - Limited ',
 'Meteora ',
 'Night Visions: Expanded Edition Canary Yellow TGT ',
 'Triple Live - Exclusive Black w/ Comeback Cover ',
 'Empire Central ',
 'IM NAYEON[POP ver.] ',
 'the mockingbird & THE CROW       explicit_lyrics ',
 'KIDZ BOP Ultimate Playlist[Lavender LP] ',

In [66]:
embeddings = get_embeddings_batch(text_to_embed)

Processed 100 of 2000
Processed 200 of 2000
Processed 300 of 2000
Processed 400 of 2000
Processed 500 of 2000
Processed 600 of 2000
Processed 700 of 2000
Processed 800 of 2000
Processed 900 of 2000
Processed 1000 of 2000
Processed 1100 of 2000
Processed 1200 of 2000
Processed 1300 of 2000
Processed 1400 of 2000
Processed 1500 of 2000
Processed 1600 of 2000
Processed 1700 of 2000
Processed 1800 of 2000
Processed 1900 of 2000
Processed 2000 of 2000

In [67]:
len(embeddings)

2000

In [73]:
pointstructs = []
i=1
for embedding, data in zip(embeddings, data_to_embed):
    pointstructs.append(
        PointStruct(
            id=i,
            vector={
                "text-embedding-3-small": embedding,
                "bm25": Document(
                    text=data["preprocessed_description"],
                    model="qdrant/bm25"
                )
            },
            payload=data
        )
    )
    i += 1

In [74]:
pointstructs[0].vector

{'text-embedding-3-small': [0.042724609375,
  0.05621337890625,
  -0.010101318359375,
  -0.00572967529296875,
  0.016204833984375,
  -0.024383544921875,
  0.026519775390625,
  -0.0190887451171875,
  -0.0170745849609375,
  -0.0032024383544921875,
  0.007793426513671875,
  0.002712249755859375,
  0.02935791015625,
  0.00855255126953125,
  -0.00327301025390625,
  0.015869140625,
  -0.010223388671875,
  -0.01104736328125,
  0.0157928466796875,
  0.037628173828125,
  0.0399169921875,
  0.052703857421875,
  0.00458526611328125,
  -0.046600341796875,
  0.05609130859375,
  0.0595703125,
  -0.00449371337890625,
  -0.0018320083618164062,
  -0.003498077392578125,
  0.0217132568359375,
  0.02777099609375,
  -0.0206298828125,
  -0.0015869140625,
  -0.014739990234375,
  -0.0341796875,
  -0.00023853778839111328,
  -0.044891357421875,
  0.022247314453125,
  0.0283355712890625,
  -0.0284271240234375,
  0.05560302734375,
  -0.0262451171875,
  0.01483917236328125,
  -0.0543212890625,
  0.0116424560546875,
  0.042022705078125,
  -0.0034503936767578125,
  0.0014944076538085938,
  -0.0141754150390625,
  0.035736083984375,
  -0.042694091796875,
  0.0174713134765625,
  -0.005001068115234375,
  0.07794189453125,
  -0.0166778564453125,
  0.043914794921875,
  -0.0188140869140625,
  0.0219879150390625,
  0.0011625289916992188,
  -0.034393310546875,
  -0.00107574462890625,
  0.03692626953125,
  -0.002429962158203125,
  0.024017333984375,
  0.0279388427734375,
  -0.0167388916015625,
  0.0015659332275390625,
  -0.025115966796875,
  0.033294677734375,
  -0.01788330078125,
  0.00710296630859375,
  -0.007518768310546875,
  -0.039764404296875,
  0.046722412109375,
  -0.022674560546875,
  -0.0101470947265625,
  -0.01515960693359375,
  -0.02691650390625,
  0.0015382766723632812,
  -0.033660888671875,
  -0.0233001708984375,
  0.0126495361328125,
  -0.01873779296875,
  0.0024967193603515625,
  -0.043609619140625,
  -0.04901123046875,
  -0.0038242340087890625,
  -0.0045623779296875,
  -0.0287322998046875,
  0.01303863525390625,
  -0.06005859375,
  0.00571441650390625,
  -0.07403564453125,
  0.0093231201171875,
  -0.02215576171875,
  0.011077880859375,
  0.06097412109375,
  0.0183868408203125,
  -0.006771087646484375,
  0.021209716796875,
  0.0340576171875,
  -0.0017309188842773438,
  -0.045501708984375,
  -0.0052642822265625,
  0.0298004150390625,
  -0.0156097412109375,
  -0.0137481689453125,
  0.019073486328125,
  -0.032012939453125,
  -0.02996826171875,
  -0.0704345703125,
  0.007511138916015625,
  0.0299224853515625,
  0.0029277801513671875,
  0.022247314453125,
  0.041656494140625,
  0.06170654296875,
  -0.024749755859375,
  -0.00978851318359375,
  0.0031375885009765625,
  0.00506591796875,
  0.007297515869140625,
  -0.0022296905517578125,
  -0.0179443359375,
  -0.0103912353515625,
  0.042083740234375,
  -0.0109710693359375,
  -0.016815185546875,
  0.005336761474609375,
  0.025787353515625,
  0.0130615234375,
  -0.00530242919921875,
  -0.0253143310546875,
  -0.034576416015625,
  0.0096435546875,
  0.005306243896484375,
  -0.00849151611328125,
  0.028900146484375,
  -0.0408935546875,
  0.033447265625,
  0.03363037109375,
  0.03564453125,
  0.0028591156005859375,
  -0.0066680908203125,
  0.0301055908203125,
  -0.00638580322265625,
  -0.038665771484375,
  0.01409149169921875,
  -0.0216064453125,
  -0.0096282958984375,
  -0.035064697265625,
  -0.0028667449951171875,
  -0.049102783203125,
  -0.005603790283203125,
  0.02227783203125,
  -0.07928466796875,
  -0.0236968994140625,
  0.00662994384765625,
  -0.031890869140625,
  -0.00713348388671875,
  0.01329803466796875,
  -0.0016202926635742188,
  -0.005687713623046875,
  -0.0230865478515625,
  -0.020111083984375,
  -0.019805908203125,
  -0.00041866302490234375,
  -0.0293121337890625,
  -0.035552978515625,
  -0.0540771484375,
  0.01062774658203125,
  -0.0139007568359375,
  -0.008636474609375,
  -0.058563232421875,
  -0.0023708343505859375,
  -0.03179931640625,
  -0.0300445556640625,
  0.0203857421875,
  -0.05908203125,
  -0.001644134521484375,
  0.007770538330078125,
  0.04730224609375,
  -0.040374755859375,
  -0.047607421875,
  -0.00327301025390625,
  0.004688262939453125,
  0.0298309326171875,
  -0.02337646484375,
  0.033050537109375,
  0.0211639404296875,
  -0.040985107421875,
  0.0479736328125,
  0.064208984375,
  0.038543701171875,
  0.0284576416015625,
  -0.01447296142578125,
  -0.0281829833984375,
  -0.0011243820190429688,
  -0.0413818359375,
  0.003345489501953125,
  0.03863525390625,
  0.04638671875,
  0.027252197265625,
  -0.0404052734375,
  -0.0024776458740234375,
  -0.01861572265625,
  -0.030029296875,
  -0.0009589195251464844,
  -0.002483367919921875,
  -0.0350341796875,
  0.09228515625,
  -0.00778961181640625,
  -0.0293121337890625,
  -0.017242431640625,
  0.006580352783203125,
  0.015838623046875,
  0.00833892822265625,
  0.00693511962890625,
  -0.007366180419921875,
  -0.038177490234375,
  -0.022674560546875,
  0.00940704345703125,
  0.01316070556640625,
  -0.00859832763671875,
  0.037994384765625,
  0.036407470703125,
  -0.01739501953125,
  -0.0288543701171875,
  0.031494140625,
  0.005184173583984375,
  -0.036407470703125,
  0.05596923828125,
  -0.0192718505859375,
  -0.0125274658203125,
  0.00038623809814453125,
  -0.037445068359375,
  0.017608642578125,
  -0.00963592529296875,
  -0.0192718505859375,
  -0.034881591796875,
  0.019012451171875,
  -0.004608154296875,
  0.00864410400390625,
  -0.006031036376953125,
  0.01849365234375,
  -0.001979827880859375,
  -0.0020046234130859375,
  0.002960205078125,
  0.0235137939453125,
  0.049041748046875,
  -0.0169677734375,
  0.028167724609375,
  0.0002918243408203125,
  -0.00013887882232666016,
  0.0267333984375,
  0.021697998046875,
  -0.01076507568359375,
  -0.01552581787109375,
  -0.0078582763671875,
  0.010650634765625,
  -0.021331787109375,
  0.010040283203125,
  -6.031990051269531e-05,
  -0.032684326171875,
  -0.037445068359375,
  0.03143310546875,
  0.04669189453125,
  -0.011932373046875,
  -0.01125335693359375,
  -0.0175323486328125,
  -0.0341796875,
  -0.042694091796875,
  0.06549072265625,
  0.04779052734375,
  -0.01837158203125,
  -0.0304412841796875,
  0.037017822265625,
  0.0125732421875,
  0.020538330078125,
  0.03631591796875,
  0.0472412109375,
  -0.03460693359375,
  0.02435302734375,
  0.01322174072265625,
  1.3709068298339844e-06,
  -0.0068206787109375,
  0.02984619140625,
  -0.00908660888671875,
  -0.029754638671875,
  0.043853759765625,
  -0.021820068359375,
  -0.0369873046875,
  0.0123748779296875,
  -0.04266357421875,
  -0.01153564453125,
  -0.013275146484375,
  0.03753662109375,
  -0.030487060546875,
  0.0159912109375,
  0.0037631988525390625,
  0.053375244140625,
  0.021209716796875,
  -0.0142364501953125,
  0.002689361572265625,
  -0.0172271728515625,
  0.043182373046875,
  -0.00797271728515625,
  -0.033294677734375,
  0.0106048583984375,
  -0.05450439453125,
  0.0279693603515625,
  0.0109710693359375,
  0.007541656494140625,
  -0.01715087890625,
  -0.0124969482421875,
  -0.03955078125,
  -0.01013946533203125,
  0.052459716796875,
  -0.0010805130004882812,
  -0.0736083984375,
  -0.040283203125,
  -0.0133209228515625,
  0.01751708984375,
  0.017303466796875,
  -0.00835418701171875,
  0.015777587890625,
  0.0218963623046875,
  0.01126861572265625,
  0.0086669921875,
  -0.047698974609375,
  -0.0108642578125,
  -0.032867431640625,
  0.0005273818969726562,
  0.0382080078125,
  0.010467529296875,
  -0.039093017578125,
  0.0019178390502929688,
  0.044525146484375,
  -0.007762908935546875,
  -0.033935546875,
  -0.00901031494140625,
  -0.07763671875,
  0.01151275634765625,
  0.02471923828125,
  0.0310516357421875,
  -0.02117919921875,
  0.0218353271484375,
  0.0205078125,
  -0.020782470703125,
  -0.004543304443359375,
  -0.0198974609375,
  -0.00662994384765625,
  0.059844970703125,
  0.033050537109375,
  0.01284027099609375,
  -0.0479736328125,
  0.06048583984375,
  -0.0246429443359375,
  0.037353515625,
  0.0986328125,
  -0.0321044921875,
  -0.00283050537109375,
  0.04803466796875,
  -7.49826431274414e-05,
  0.00432586669921875,
  0.007415771484375,
  -0.038421630859375,
  0.00435638427734375,
  -0.0361328125,
  0.01470947265625,
  -0.0035114288330078125,
  -0.020904541015625,
  0.01995849609375,
  0.016357421875,
  0.0028972625732421875,
  0.0010433197021484375,
  0.01053619384765625,
  -0.03717041015625,
  0.05523681640625,
  0.0072479248046875,
  -0.080810546875,
  0.00608062744140625,
  0.020172119140625,
  -0.020355224609375,
  -0.00392913818359375,
  0.04339599609375,
  -0.01788330078125,
  -0.00991058349609375,
  -0.052642822265625,
  -0.005397796630859375,
  0.01629638671875,
  0.01021575927734375,
  0.033935546875,
  -0.00687408447265625,
  0.037506103515625,
  0.00058746337890625,
  0.022186279296875,
  0.047454833984375,
  -0.0811767578125,
  -0.013519287109375,
  0.022735595703125,
  0.004352569580078125,
  -0.040679931640625,
  -0.0001361370086669922,
  0.034393310546875,
  0.0015211105346679688,
  0.0198822021484375,
  0.025787353515625,
  0.01358795166015625,
  -0.01053619384765625,
  -0.04400634765625,
  -0.029541015625,
  -0.00063323974609375,
  0.0584716796875,
  0.015777587890625,
  -0.005161285400390625,
  -0.0193634033203125,
  -0.0167236328125,
  -0.01715087890625,
  0.051239013671875,
  -0.0165557861328125,
  -0.033935546875,
  -0.03607177734375,
  -0.00579071044921875,
  -0.00873565673828125,
  0.01187896728515625,
  0.01526641845703125,
  -0.05694580078125,
  -0.027801513671875,
  -0.0538330078125,
  -0.06683349609375,
  0.031707763671875,
  0.0052490234375,
  0.0155487060546875,
  0.0369873046875,
  -0.069580078125,
  0.0246734619140625,
  -0.0189666748046875,
  0.043609619140625,
  -0.0228118896484375,
  0.019012451171875,
  -0.004161834716796875,
  0.00250244140625,
  0.027862548828125,
  0.01015472412109375,
  -0.00212860107421875,
  0.018707275390625,
  -0.0450439453125,
  -0.0498046875,
  -0.0160064697265625,
  -0.039398193359375,
  0.0223388671875,
  0.034332275390625,
  0.019500732421875,
  0.027618408203125,
  0.038604736328125,
  0.0188446044921875,
  0.0210723876953125,
  -0.02618408203125,
  0.00962066650390625,
  0.044708251953125,
  0.0211944580078125,
  -0.0198211669921875,
  0.03143310546875,
  0.0225067138671875,
  0.005748748779296875,
  0.024932861328125,
  0.00885772705078125,
  0.01110076904296875,
  0.0297088623046875,
  -0.016082763671875,
  -0.0070343017578125,
  -0.0304718017578125,
  -0.01340484619140625,
  0.003658294677734375,
  -0.00899505615234375,
  -0.0209197998046875,
  0.0631103515625,
  0.04547119140625,
  0.028778076171875,
  -0.0010890960693359375,
  0.04644775390625,
  0.0072784423828125,
  -0.0215301513671875,
  -0.01195526123046875,
  -0.0926513671875,
  -0.00907135009765625,
  -0.0011501312255859375,
  -0.002262115478515625,
  -0.0281829833984375,
  -0.058685302734375,
  0.039154052734375,
  -0.00701141357421875,
  -0.0111846923828125,
  -0.01216888427734375,
  -0.01157379150390625,
  -0.0195159912109375,
  0.0094757080078125,
  -0.060577392578125,
  -0.032470703125,
  -0.0198516845703125,
  -0.021026611328125,
  0.0163421630859375,
  -0.0039825439453125,
  0.05230712890625,
  0.03363037109375,
  0.0012426376342773438,
  -0.00347137451171875,
  -0.02978515625,
  -0.005771636962890625,
  -0.0093841552734375,
  -0.0214691162109375,
  0.00403594970703125,
  -0.032806396484375,
  0.039398193359375,
  0.018829345703125,
  -0.0153656005859375,
  0.01491546630859375,
  0.00925445556640625,
  0.00833892822265625,
  -0.01194000244140625,
  0.01837158203125,
  0.029022216796875,
  -0.0097503662109375,
  0.007045745849609375,
  -0.028472900390625,
  0.007114410400390625,
  -0.00893402099609375,
  -0.0162811279296875,
  -0.0010318756103515625,
  -0.00042128562927246094,
  -0.0309600830078125,
  0.0316162109375,
  0.027923583984375,
  0.0017385482788085938,
  -0.02044677734375,
  -0.0207977294921875,
  -0.0078887939453125,
  -0.004024505615234375,
  -0.0284576416015625,
  0.042755126953125,
  0.0192108154296875,
  0.01336669921875,
  -0.0205230712890625,
  -0.027496337890625,
  -0.014007568359375,
  -0.0198822021484375,
  -0.020782470703125,
  -0.0081939697265625,
  0.031158447265625,
  0.004627227783203125,
  -0.015655517578125,
  -0.0218353271484375,
  -0.00629425048828125,
  -0.00919342041015625,
  -0.017242431640625,
  0.00011307001113891602,
  -0.02056884765625,
  0.005474090576171875,
  0.0298309326171875,
  0.0226287841796875,
  0.008453369140625,
  0.01171875,
  -0.03424072265625,
  -0.01678466796875,
  0.043609619140625,
  -0.020263671875,
  0.0302276611328125,
  0.00528717041015625,
  -0.0150146484375,
  -0.03851318359375,
  0.01053619384765625,
  0.0020351409912109375,
  -0.0538330078125,
  -0.004486083984375,
  -0.0257568359375,
  -0.0045013427734375,
  0.0240936279296875,
  -0.01507568359375,
  0.0031147003173828125,
  -0.0160369873046875,
  -0.0253143310546875,
  0.0131988525390625,
  -0.02056884765625,
  -0.0177154541015625,
  0.0038394927978515625,
  0.0125885009765625,
  -0.0117645263671875,
  0.00656890869140625,
  0.019134521484375,
  -0.03997802734375,
  -0.0289764404296875,
  -0.001659393310546875,
  -0.016571044921875,
  0.0298004150390625,
  -0.0031108856201171875,
  -0.0185394287109375,
  0.00738525390625,
  -0.03192138671875,
  -0.0166778564453125,
  0.007480621337890625,
  -0.01885986328125,
  -0.00904083251953125,
  0.002658843994140625,
  0.0263671875,
  0.0036830902099609375,
  0.0142364501953125,
  -0.0401611328125,
  0.02105712890625,
  0.018524169921875,
  -0.0216827392578125,
  0.03961181640625,
  0.045166015625,
  -0.032928466796875,
  0.0003428459167480469,
  -0.01377105712890625,
  -0.0012865066528320312,
  -0.008544921875,
  -0.00879669189453125,
  -0.01513671875,
  -0.045257568359375,
  0.038330078125,
  0.029388427734375,
  0.0006089210510253906,
  -0.0011167526245117188,
  0.0290679931640625,
  -0.0214691162109375,
  -0.022796630859375,
  0.032806396484375,
  -0.0085906982421875,
  -0.040252685546875,
  -0.0162200927734375,
  0.00444793701171875,
  -0.015655517578125,
  -0.01526641845703125,
  -0.018646240234375,
  -0.0313720703125,
  0.01367950439453125,
  0.007274627685546875,
  0.0024852752685546875,
  0.0384521484375,
  -0.0055389404296875,
  0.028778076171875,
  -0.026885986328125,
  0.04095458984375,
  -0.007671356201171875,
  -0.01009368896484375,
  0.016265869140625,
  -0.018768310546875,
  -0.01103973388671875,
  0.015716552734375,
  -0.031097412109375,
  0.0224456787109375,
  -0.0265960693359375,
  0.007610321044921875,
  0.00666046142578125,
  -0.01404571533203125,
  -0.030517578125,
  0.012237548828125,
  -0.03533935546875,
  0.002742767333984375,
  0.044769287109375,
  0.021636962890625,
  -0.04541015625,
  0.0217437744140625,
  -0.002368927001953125,
  -0.006084442138671875,
  0.0105438232421875,
  0.006622314453125,
  0.001190185546875,
  0.0533447265625,
  0.038543701171875,
  0.0186004638671875,
  -0.03472900390625,
  -0.00798797607421875,
  -0.0126800537109375,
  0.007152557373046875,
  -0.0137481689453125,
  -0.003490447998046875,
  -0.0002689361572265625,
  -0.0570068359375,
  -0.021942138671875,
  -0.032806396484375,
  0.01157379150390625,
  0.0010547637939453125,
  -0.0139312744140625,
  0.035064697265625,
  0.0207061767578125,
  0.007320404052734375,
  -0.02801513671875,
  -0.0203704833984375,
  0.007366180419921875,
  0.0167999267578125,
  -0.015838623046875,
  0.033172607421875,
  -0.0679931640625,
  -0.0024547576904296875,
  -0.0174102783203125,
  -0.00897979736328125,
  -0.0760498046875,
  -0.037689208984375,
  0.0072174072265625,
  0.01236724853515625,
  0.0094451904296875,
  -0.029388427734375,
  0.0194549560546875,
  -0.0193023681640625,
  0.02655029296875,
  0.023162841796875,
  0.005084991455078125,
  -0.0275726318359375,
  0.00975799560546875,
  0.00860595703125,
  -0.0018138885498046875,
  -0.01207733154296875,
  -0.011505126953125,
  -0.0033359527587890625,
  -0.02764892578125,
  0.024993896484375,
  -0.0228729248046875,
  -0.005321502685546875,
  0.038299560546875,
  -0.0126953125,
  0.01227569580078125,
  0.040985107421875,
  -0.0303955078125,
  -0.0268096923828125,
  -0.00464630126953125,
  -0.0404052734375,
  -0.04132080078125,
  0.06072998046875,
  0.04815673828125,
  -0.006526947021484375,
  0.014556884765625,
  -0.01084136962890625,
  0.006439208984375,
  0.018707275390625,
  -0.024627685546875,
  0.0108642578125,
  0.0027294158935546875,
  0.037017822265625,
  -0.0237884521484375,
  -0.0011987686157226562,
  0.00392913818359375,
  -0.0010137557983398438,
  0.035614013671875,
  -0.0019588470458984375,
  0.03839111328125,
  0.013336181640625,
  -0.01971435546875,
  -0.02154541015625,
  0.00860595703125,
  0.0009322166442871094,
  0.0034351348876953125,
  0.0036334991455078125,
  -0.051422119140625,
  0.0015687942504882812,
  -0.034423828125,
  -0.01287841796875,
  0.004436492919921875,
  0.0092926025390625,
  0.03594970703125,
  -0.03192138671875,
  -0.0018568038940429688,
  0.041229248046875,
  -0.0263671875,
  -0.043487548828125,
  0.0107879638671875,
  0.0093536376953125,
  0.0008182525634765625,
  -0.0235443115234375,
  -0.007106781005859375,
  0.0106201171875,
  -0.000644683837890625,
  -0.0251922607421875,
  -0.005466461181640625,
  0.021240234375,
  0.0233612060546875,
  -0.02630615234375,
  0.01436614990234375,
  0.00022983551025390625,
  0.01690673828125,
  0.0123748779296875,
  0.027008056640625,
  0.024627685546875,
  -0.04010009765625,
  0.032440185546875,
  0.01366424560546875,
  0.031524658203125,
  -0.01457977294921875,
  0.020111083984375,
  -0.038543701171875,
  0.005096435546875,
  0.00469970703125,
  0.01505279541015625,
  0.01309967041015625,
  -0.037506103515625,
  -0.03369140625,
  0.00984954833984375,
  0.0189056396484375,
  0.015380859375,
  -0.01806640625,
  0.0191650390625,
  0.0226898193359375,
  0.04278564453125,
  -0.07525634765625,
  -0.007213592529296875,
  0.021209716796875,
  0.01490020751953125,
  -0.0141754150390625,
  -0.031219482421875,
  0.0175628662109375,
  -0.0008716583251953125,
  -0.01203155517578125,
  0.01110076904296875,
  0.023284912109375,
  -0.0020389556884765625,
  0.0264434814453125,
  -0.0239715576171875,
  0.0084228515625,
  -0.0039215087890625,
  -0.00885009765625,
  -0.00835418701171875,
  -0.0003027915954589844,
  -0.0043792724609375,
  0.018768310546875,
  -0.006496429443359375,
  -0.013885498046875,
  0.0452880859375,
  0.006900787353515625,
  -0.016693115234375,
  0.006740570068359375,
  -0.0072784423828125,
  -0.023162841796875,
  0.01861572265625,
  -0.0172882080078125,
  -0.022796630859375,
  0.027801513671875,
  0.0284576416015625,
  0.0022563934326171875,
  0.005947113037109375,
  -0.030609130859375,
  0.0138092041015625,
  -0.0051422119140625,
  -0.01165771484375,
  0.0188140869140625,
  0.0195159912109375,
  -0.0034923553466796875,
  -0.007415771484375,
  0.0294647216796875,
  -0.0272369384765625,
  -0.060791015625,
  0.0238800048828125,
  -0.023468017578125,
  -0.017669677734375,
  -0.0011844635009765625,
  -0.0173492431640625,
  0.01296234130859375,
  -0.00605010986328125,
  -0.0289764404296875,
  -0.0234832763671875,
  -0.01800537109375,
  -0.018585205078125,
  0.0016298294067382812,
  0.01287841796875,
  -0.035980224609375,
  0.0657958984375,
  -0.00959014892578125,
  0.0276031494140625,
  0.0404052734375,
  -0.01195526123046875,
  0.018890380859375,
  0.006622314453125,
  -0.0103302001953125,
  0.0191497802734375,
  -0.01271820068359375,
  0.02154541015625,
  0.024444580078125,
  0.01334381103515625,
  -0.04107666015625,
  -0.013458251953125,
  0.059844970703125,
  0.0249176025390625,
  -0.006511688232421875,
  -0.048004150390625,
  0.02001953125,
  0.0113983154296875,
  0.01372528076171875,
  -0.0257415771484375,
  0.0285491943359375,
  0.060150146484375,
  -0.02398681640625,
  -0.0333251953125,
  0.028289794921875,
  -0.027862548828125,
  -0.010345458984375,
  0.014434814453125,
  -0.0065765380859375,
  0.01453399658203125,
  -0.003314971923828125,
  -0.005016326904296875,
  -0.0143280029296875,
  0.0186614990234375,

In [75]:
COLLECTION_NAME = "Amazon-items-collection-01-hybrid-search"
BATCH_SIZE = 500

for start in range(0, len(pointstructs), BATCH_SIZE):
    batch = pointstructs[start : start + BATCH_SIZE]
    qdrant_client.upsert(
        collection_name=COLLECTION_NAME,
        points=batch,
        wait=True,
    )
    print(f"Upserted {start + len(batch)} / {len(pointstructs)}")

Upserted 500 / 2000
Upserted 1000 / 2000
Upserted 1500 / 2000
Upserted 2000 / 2000

### Hybrid Retrieval

In [ ]:
def retrieve_data(query, k=5):

    query_embedding = get_embedding(query)

    results = qdrant_client.query_points(
        collection_name="Amazon-items-collection-01-hybrid-search",
        prefetch=[
            Prefetch(
                query=query_embedding,
                using="text-embedding-3-small",
                limit=20
            ),
            Prefetch(
                query=Document(
                    text=query,
                    model="qdrant/bm25"
                ),
                using="bm25",
                limit=20
            )
        ],
        query=FusionQuery(fusion="rrf"),
        limit=k
    )

    retrieved_context_ids = []
    retrieved_context = []
    similarity_scores = []
    retrieved_context_ratings = []

    for result in results.points:
        retrieved_context_ids.append(result.payload["parent_asin"])
        retrieved_context.append(result.payload["preprocessed_description"])
        similarity_scores.append(result.score)
        retrieved_context_ratings.append(result.payload["average_rating"])

    return {
        "retrieved_context_ids": retrieved_context_ids,
        "retrieved_context": retrieved_context,
        "similarity_scores": similarity_scores,
        "retrieved_context_ratings": retrieved_context_ratings
/    }

In [77]:
results = retrieve_data("Best song of the summer?", k=20)

In [78]:
results

{'retrieved_context_ids': ['B09XGWCB4B',
  'B09XGWCB4B',
  'B09Y4X2XTS',
  'B09Y4X2XTS',
  'B09NFQ6593',
  'B09NFQ6593',
  'B0C1SWKV9J',
  'B0C1SWKV9J',
  'B0B14D2HZ6',
  'B09RG97953',
  'B09RG97953',
  'B0BLZG2YMG',
  'B0B14D2HZ6',
  'B0BLZG2YMG',
  'B09RRZYVPL',
  'B09RRZYVPL',
  'B0B28N7NKP',
  'B0B28N7NKP',
  'B0BTB6DFSW',
  'B0BTB6DFSW'],
 'retrieved_context': ['Sounds Of Summer: The Very Best Of The Beach Boys[Remastered] ',
  'Sounds Of Summer: The Very Best Of The Beach Boys[Remastered] ',
  'Songs About You ',
  'Songs About You ',
  'Summer Of Soul ...Or, When The Revolution Could Not Be Televised Soundtrack ',
  'Summer Of Soul ...Or, When The Revolution Could Not Be Televised Soundtrack ',
  'Stick Season       Explicit Lyrics ',
  'Stick Season       Explicit Lyrics ',
  'Donna Summer: 40th Anniversary Picture ',
  'Dawn FM by The Weekend Autograph       explicit_lyrics ',
  'Dawn FM by The Weekend Autograph       explicit_lyrics ',
  'Listen To The Music ',
  'Donna Summer: 40th Anniversary Picture ',
  'Listen To The Music ',
  "Tell Me That It's Over ",
  "Tell Me That It's Over ",
  'Survivor Blues - Blue ',
  'Survivor Blues - Blue ',
  'Greatest Hits : My Prerogative ',
  'Greatest Hits : My Prerogative '],
 'similarity_scores': [1.0999999,
  1.0833334,
  0.625,
  0.5396825,
  0.4666667,
  0.4155844,
  0.37500003,
  0.33333334,
  0.25,
  0.25,
  0.23076925,
  0.2142857,
  0.2,
  0.2,
  0.1875,
  0.1764706,
  0.16666667,
  0.15789473,
  0.15,
  0.14285715],
 'retrieved_context_ratings': [4.7,
  4.7,
  4.8,
  4.8,
  4.5,
  4.5,
  4.7,
  4.7,
  4.7,
  4.7,
  4.7,
  4.7,
  4.7,
  4.7,
  4.8,
  4.8,
  4.7,
  4.7,
  4.7,
  4.7]}

### Hybrid Search with weighted RRF

In [ ]:
def retrieve_data(query, k=5):

    query_embedding = get_embedding(query)

    results = qdrant_client.query_points(
        collection_name="Amazon-items-collection-01-hybrid-search",
        prefetch=[
            Prefetch(
                query=query_embedding,
                using="text-embedding-3-small",
                limit=20
            ),
            Prefetch(
                query=Document(
                    text=query,
                    model="qdrant/bm25"
                ),
                using="bm25",
                limit=20
            )
        ],
        query=models.RrfQuery(rrf=models.Rrf(weights=[3,1])),
        limit=k
    )

    retrieved_context_ids = []
    retrieved_context = []
    similarity_scores = []
    retrieved_context_ratings = []

    for result in results.points:
        retrieved_context_ids.append(result.payload["parent_asin"])
        retrieved_context.append(result.payload["preprocessed_description"])
        similarity_scores.append(result.score)
        retrieved_context_ratings.append(result.payload["average_rating"])

    return {
        "retrieved_context_ids": retrieved_context_ids,
        "retrieved_context": retrieved_context,
        "similarity_scores": similarity_scores,
        "retrieved_context_ratings": retrieved_context_ratings
    }

In [92]:
results = retrieve_data("whats a good charlie brown summer song?", k=20)

In [93]:
results

{'retrieved_context_ids': ['B09XSX514Q',
  'B0B9BX5C4K',
  'B0B9BX5C4K',
  'B09XSX514Q',
  'B0BFRRZPP8',
  'B0BFRRZPP8',
  'B09XGWCB4B',
  'B09XGWCB4B',
  'B09NFQ6593',
  'B09NFQ6593',
  'B09PK47CGG',
  'B09PK47CGG',
  'B0B832LSNC',
  'B0B832LSNC',
  'B0BBRNMGSZ',
  'B0BBRNMGSZ',
  'B0BFLT4TJT',
  'B0BFLT4TJT',
  'B09TQJ69KH',
  'B09TQJ69KH'],
 'retrieved_context': ["It's The Great Pumpkin, Charlie Brown[45rpm LP] ",
  'A Charlie Brown Christmas (Deluxe Edition) ',
  'A Charlie Brown Christmas (Deluxe Edition) ',
  "It's The Great Pumpkin, Charlie Brown[45rpm LP] ",
  'CHARLIE ',
  'CHARLIE ',
  'Sounds Of Summer: The Very Best Of The Beach Boys[Remastered] ',
  'Sounds Of Summer: The Very Best Of The Beach Boys[Remastered] ',
  'Summer Of Soul ...Or, When The Revolution Could Not Be Televised Soundtrack ',
  'Summer Of Soul ...Or, When The Revolution Could Not Be Televised Soundtrack ',
  'SLEEPLESS IN SEATTLE--Original Motion Picture Soundtrack (Sunset Vinyl Edition) ',
  'SLEEPLESS IN SEATTLE--Original Motion Picture Soundtrack (Sunset Vinyl Edition) ',
  'When Christmas Comes Around... ',
  'When Christmas Comes Around... ',
  'A Neil Diamond Christmas ',
  'A Neil Diamond Christmas ',
  "Everybody Knows It's Christmas[Candy Floss LP] ",
  "Everybody Knows It's Christmas[Candy Floss LP] ",
  'Lil G.L. Presents: Jukebox Charley ',
  'Lil G.L. Presents: Jukebox Charley '],
 'similarity_scores': [1.05,
  1.0,
  0.9047619,
  0.8666667,
  0.54444444,
  0.4909091,
  0.4224599,
  0.38596493,
  0.36324787,
  0.3482143,
  0.26666668,
  0.25,
  0.23529412,
  0.22222222,
  0.21052632,
  0.2,
  0.1904762,
  0.18181819,
  0.17391305,
  0.16666667],
 'retrieved_context_ratings': [4.8,
  4.8,
  4.8,
  4.8,
  4.7,
  4.7,
  4.7,
  4.7,
  4.5,
  4.5,
  4.8,
  4.8,
  4.8,
  4.8,
  4.5,
  4.5,
  4.6,
  4.6,
  4.8,
  4.8]}